export const TowerTypes = {
  archer: {
    name: "Archer",
    description:
      "Archer tower, the first and most affordable tower. Basic range, with basic fire rate and low damage",
    lvl: [
      {
        cost: 50,
        range: 120,
        fireRate: 1000,
        unit: 1,
        damage: 25,
        frames: 1,
        sprites: ["/assets/sprites/Towers/Idle/Archer/lvl1/lvl1_1.png"],
        buildSprites: Array.from({length: 4}, (_, i) => `/assets/sprites/Towers/Upgrade/lvl1/build_1_${i}.png`),
        description: "Mid range, Mid firerate and Low damage",
      },
      {
        cost: 75,
        range: 120,
        fireRate: 1000,
        unit: 1,
        damage: 35,
        frames: 4,
        sprites: Array.from({length: 4}, (_, i) => `/assets/sprites/Towers/Idle/Archer/lvl2/lvl2_${i+1}.png`),
        buildSprites: Array.from({length: 4}, (_, i) => `/assets/sprites/Towers/Upgrade/lvl2/build_2_${i}.png`),
        description: "Damage and Range upgraded",
      },
      {
        cost: 100,
        range: 120,
        fireRate: 1000,
        unit: 1,
        damage: 50,
        frames: 4,
        sprites: Array.from({length: 4}, (_, i) => `/assets/sprites/Towers/Idle/Archer/lvl3/lvl3_${i+1}.png`),
        buildSprites: Array.from({length: 4}, (_, i) => `/assets/sprites/Towers/Upgrade/lvl3/build_3_${i}.png`),
        description: "Damage upgraded",
      },
      {
        cost: 125,
        range: 140,
        fireRate: 900,
        unit: -1,
        damage: 60,
        frames: 6,
        sprites: Array.from({length: 6}, (_, i) => `/assets/sprites/Towers/Idle/Archer/lvl4/lvl4_${i+1}.png`),
        buildSprites: Array.from({length: 4}, (_, i) => `/assets/sprites/Towers/Upgrade/lvl4/build_4_${i}.png`),
        description: "Damage, Range and Firerate upgraded",
      },
      {
        cost: 150,
        range: 150,
        fireRate: 900,
        unit: 2,
        damage: 65,
        frames: 6,
        sprites: Array.from({length: 6}, (_, i) => `/assets/sprites/Towers/Idle/Archer/lvl5/lvl5_${i+1}.png`),
        buildSprites: Array.from({length: 4}, (_, i) => `/assets/sprites/Towers/Upgrade/lvl5/build_5_${i}.png`),
        description: "Range and Damage upgraded",
      },
      {
        cost: 175,
        range: 160,
        fireRate: 800,
        unit: 3,
        damage: 75,
        frames: 6,
        sprites: Array.from({length: 6}, (_, i) => `/assets/sprites/Towers/Idle/Archer/lvl6/lvl6_${i+1}.png`),
        buildSprites: Array.from({length: 4}, (_, i) => `/assets/sprites/Towers/Upgrade/lvl6/build_6_${i}.png`),
        description: "Damage, Range and Firerate upgraded",
      },
      {
        cost: 200,
        range: 170,
        fireRate: 800,
        unit: -1,
        damage: 90,
        frames: 6,
        sprites: Array.from({length: 6}, (_, i) => `/assets/sprites/Towers/Idle/Archer/lvl7/lvl7_${i+1}.png`),
        buildSprites: Array.from({length: 4}, (_, i) => `/assets/sprites/Towers/Upgrade/lvl7/build_7_${i}.png`),
        description: "Damage and Range upgraded",
      },
    ],
  },
  towerPlacemnt: [
    "/assets/sprites/Towers/PlaceForTower1.png",
    "/assets/sprites/Towers/PlaceForTower2.png",
  ],
};
